all: f0 f1
	# Done
f1: f1.cpp display.h
	g++ f1.cpp --std=c++11 -o f1 -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives
f0: f0.cpp display.h
	g++ f0.cpp --std=c++11 -o f0 -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives
