all: dynablaster
	# Done
dynablaster: dynablaster.cpp
	g++ -g --std=c++11 dynablaster.cpp -o dynablaster -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_image
